In [1]:
from scipy import interpolate
from numpy import polynomial as P

In [3]:
import numpy as np
import pandas as pd
from scipy import linalg
import matplotlib.pyplot as plt

In [17]:
%config InlineBackend.figure_format='svg' #'png2x','svg','jpeg','pdf','png','jpg','retina'

$$
\text{自定义命令}  
\newcommand{\inner}[2]{{\langle #1,#2\rangle}}
\newcommand{\dlim}{\displaystyle \lim}  
\newcommand{\dint}{\displaystyle \int}   
\newcommand{\ra}{\rangle}  
\newcommand{\la}{\langle}   
\newcommand{\inner}[2]{{\langle #1,#2\rangle}}
\newcommand{\x}{\mathbf{x}}   
\newcommand{\xt}{\mathbf{x}^{\mathsf{T}}}   
\newcommand{\T}{{\mathsf{T}}}
\newcommand{\abf}{\mathbf{a}}   
\newcommand{\abft}{\mathbf{a}^{\mathsf{T}}}   
\newcommand{\R}{\mathbb{R}}   
\newcommand{\C}{\mathbb{C}}   
\newcommand{\E}{\mathrm{e}}   
\newcommand{\F}{\mathbb{F}}   
\newcommand{\X}{\mathbf{X}}   
\newcommand{\Y}{\mathbf{Y}}  
\newcommand{\f}{\mathbf{f}}  
\newcommand{\U}{\mathbf{u}}   
\newcommand{\D}{\mathrm{d}}  
\newcommand{\M}{\mathcal{M}}  
\newcommand{\LL}{\mathcal{L}}  
\newcommand{\nullspace}{\mathrm{null}}   
\newcommand{\range}{\mathrm{range}}   
\newcommand{\Sum}[2]{{\sum_{#1}^{#2}}}   
\newcommand{\Union}[2]{{\bigcup_{#1}^{#2}}}   
\newcommand{\Intersection}[2]{{\bigcap_{#1}^{#2}}}   
\newcommand{\pd}[1]{\frac{\partial}{\partial #1}} \notag
$$  

# Ploynomials

Suppose p is a polynomial, then 
   
Method| Descriptions
-----|-----
p.roots()
p.coef
p.domain
p.window

In [12]:
p1 = P.Polynomial([1,2,3],domain=[-1,1],window=[-1,1])
p1

Polynomial([1., 2., 3.], domain=[-1.,  1.], window=[-1.,  1.])

In [18]:
type(p1)

numpy.polynomial.polynomial.Polynomial

In [20]:
p1.roots()

array([-0.33333333-0.47140452j, -0.33333333+0.47140452j])

In [16]:
p2 = P.Polynomial.fromroots([-1,1])
p2

Polynomial([-1.,  0.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [24]:
p1+p2

Polynomial([0., 2., 4.], domain=[-1.,  1.], window=[-1.,  1.])

# Ploynomial Interpolation

In [25]:
x = np.array([1,2,3,4])
y = np.array([1,3,5,4])

In [29]:
deg = len(x) - 1
A = P.polynomial.polyvander(x, deg)
A

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.],
       [ 1.,  4., 16., 64.]])

In [30]:
c = linalg.solve(A,y)
c

array([ 2. , -3.5,  3. , -0.5])

In [35]:
f1 = P.Polynomial(c)
f1

Polynomial([ 2. , -3.5,  3. , -0.5], domain=[-1,  1], window=[-1,  1])

In [41]:
f1b = P.Polynomial.fit(x,y,deg)
f1b(4)

3.9999999999999987

# Spline Interpolation