In [4]:
import numpy as np

## Numpy的优势

In [6]:
my_arr = np.arange(10000000)
my_list = list(range(10000000))

In [9]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 131 ms


In [10]:
%time for _ in range(10): my_list2 = my_list*2

Wall time: 1.55 s


## Array

|Operation|Description|
|---|---|
|np.array()|
|np.zeros()|
|np.arange()| 
|| 
|| 
||
||
||

In [13]:
data = np.random.randn(2,3)

In [20]:
print(data)
print(data*10)
print(data+data)

[[ 1.11207648 -0.30395232 -0.60734748]
 [ 0.15519316  0.08769426  1.87371738]]
[[11.12076478 -3.03952319 -6.07347482]
 [ 1.55193163  0.87694259 18.73717381]]
[[ 2.22415296 -0.60790464 -1.21469496]
 [ 0.31038633  0.17538852  3.74743476]]


In [25]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [28]:
#Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [29]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2.shape

(2, 4)